{{- $caBundle := .Values.webhook.caBundle -}}
{{- if and (not .Values.certManager.enabled) .Values.webhook.selfSigned.enabled }}
{{- $serviceDNS := printf "sandbox-operator-webhook.%s.svc" .Values.namespace -}}
{{- $ca := genCA "sandbox-operator-webhook-ca" 3650 -}}
{{- $cert := genSignedCert $serviceDNS nil (list "sandbox-operator-webhook" (printf "sandbox-operator-webhook.%s" .Values.namespace) $serviceDNS (printf "%s.cluster.local" $serviceDNS)) 3650 $ca -}}
{{- $caBundle = ($ca.Cert | b64enc) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.webhook.tlsSecretName }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
---
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: sandbox-operator-webhook
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app.kubernetes.io/name: sandbox-operator
  ports:
    - port: 443
      targetPort: webhook
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: sandbox-operator-mutating-webhook
{{- if .Values.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Values.namespace }}/sandbox-operator-serving-cert
{{- end }}
webhooks:
  - name: msandboxtemplate.sandbox.kce.ksyun.com
    admissionReviewVersions: ["v1"]
    sideEffects: NoneOnDryRun
    failurePolicy: Fail
    matchPolicy: Equivalent
    timeoutSeconds: 10
    clientConfig:
{{- if not .Values.certManager.enabled }}
      caBundle: {{ $caBundle | quote }}
{{- end }}
      service:
        namespace: {{ .Values.namespace }}
        name: sandbox-operator-webhook
        path: /mutate-sandbox-kce-ksyun-com-v1alpha1-sandboxtemplate
    rules:
      - apiGroups: ["sandbox.kce.ksyun.com"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE"]
        resources: ["sandboxtemplates"]
  - name: msandbox.sandbox.kce.ksyun.com
    admissionReviewVersions: ["v1"]
    sideEffects: NoneOnDryRun
    failurePolicy: Fail
    matchPolicy: Equivalent
    timeoutSeconds: 10
    clientConfig:
{{- if not .Values.certManager.enabled }}
      caBundle: {{ $caBundle | quote }}
{{- end }}
      service:
        namespace: {{ .Values.namespace }}
        name: sandbox-operator-webhook
        path: /mutate-sandbox-kce-ksyun-com-v1alpha1-sandbox
    rules:
      - apiGroups: ["sandbox.kce.ksyun.com"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE"]
        resources: ["sandboxes"]
  - name: msandboxclaim.sandbox.kce.ksyun.com
    admissionReviewVersions: ["v1"]
    sideEffects: NoneOnDryRun
    failurePolicy: Fail
    matchPolicy: Equivalent
    timeoutSeconds: 10
    clientConfig:
{{- if not .Values.certManager.enabled }}
      caBundle: {{ $caBundle | quote }}
{{- end }}
      service:
        namespace: {{ .Values.namespace }}
        name: sandbox-operator-webhook
        path: /mutate-sandbox-kce-ksyun-com-v1alpha1-sandboxclaim
    rules:
      - apiGroups: ["sandbox.kce.ksyun.com"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE"]
        resources: ["sandboxclaims"]
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: sandbox-operator-validating-webhook
{{- if .Values.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Values.namespace }}/sandbox-operator-serving-cert
{{- end }}
webhooks:
  - name: vsandboxtemplate.sandbox.kce.ksyun.com
    admissionReviewVersions: ["v1"]
    sideEffects: NoneOnDryRun
    failurePolicy: Fail
    matchPolicy: Equivalent
    timeoutSeconds: 10
    clientConfig:
{{- if not .Values.certManager.enabled }}
      caBundle: {{ $caBundle | quote }}
{{- end }}
      service:
        namespace: {{ .Values.namespace }}
        name: sandbox-operator-webhook
        path: /validate-sandbox-kce-ksyun-com-v1alpha1-sandboxtemplate
    rules:
      - apiGroups: ["sandbox.kce.ksyun.com"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE", "DELETE"]
        resources: ["sandboxtemplates"]
  - name: vsandbox.sandbox.kce.ksyun.com
    admissionReviewVersions: ["v1"]
    sideEffects: NoneOnDryRun
    failurePolicy: Fail
    matchPolicy: Equivalent
    timeoutSeconds: 10
    clientConfig:
{{- if not .Values.certManager.enabled }}
      caBundle: {{ $caBundle | quote }}
{{- end }}
      service:
        namespace: {{ .Values.namespace }}
        name: sandbox-operator-webhook
        path: /validate-sandbox-kce-ksyun-com-v1alpha1-sandbox
    rules:
      - apiGroups: ["sandbox.kce.ksyun.com"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE", "DELETE"]
        resources: ["sandboxes"]
  - name: vsandboxclaim.sandbox.kce.ksyun.com
    admissionReviewVersions: ["v1"]
    sideEffects: NoneOnDryRun
    failurePolicy: Fail
    matchPolicy: Equivalent
    timeoutSeconds: 10
    clientConfig:
{{- if not .Values.certManager.enabled }}
      caBundle: {{ $caBundle | quote }}
{{- end }}
      service:
        namespace: {{ .Values.namespace }}
        name: sandbox-operator-webhook
        path: /validate-sandbox-kce-ksyun-com-v1alpha1-sandboxclaim
    rules:
      - apiGroups: ["sandbox.kce.ksyun.com"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE", "DELETE"]
        resources: ["sandboxclaims"]
